[build]
  publish = "."
  
# Environment variables for local development
[context.dev.environment]
  # Adicione suas variáveis de ambiente aqui para desenvolvimento local
  # Exemplo:
  # SUPABASE_URL = "sua-url-do-supabase"
  # SUPABASE_KEY = "sua-chave-publica-do-supabase"
  # GEMINI_API_KEY = "sua-chave-da-api-gemini"
  
# Environment variables for production
[context.production.environment]
  # Para produção, defina as variáveis através da interface do Netlify
  # ou usando o Netlify CLI com o comando:
  # netlify env:set VARIABLE_NAME "value" --secret